planets:
  goes-16:
    color: natural_color
    size: 640
    x: 500
    y: 500
  sentinel:
    height: 400
    latitude: 20.0
    longitude: 9.0
    scale: 400
    width: 400
    x: 1000
    y: 1000
settings:
  bg-color: '#000000'
  height: 1080
  width: 1920
