planets:
  goes-17:
    color: geocolor
    size: 600
    x: 400
    y: 500
  sdo:
    bandwidth: '0171'
    size: 500
    x: 0
    y: 0
  sentinel:
    height: 40
    latitude: 0
    longitude: 234
    scale: 0
    width: 40
    x: 900
    y: 900
settings:
  bg-color: '#000000'
  height: 1080
  width: 1920
