planets:
  goes-16:
    color: natural_color
    size: 640
    x: 100
    y: 100
  meteosat-11:
    color: geocolor
    size: 1000
    x: 960
    y: 540
settings:
  bg-color: '#ffffff'
  height: 1080
  width: 1920
